---
kind: pipeline
name: default
trigger:
  branch:
  - master
steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: robbof/homepage
    dockerfile: ./app/Dockerfile
    context: ./app
    tags: 
      - latest
      - ${DRONE_COMMIT_SHA}
