---
kind: pipeline
name: default
trigger:
  event:
  - tag
steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: robbof/homepage
    dockerfile: ./app/Dockerfile
    context: ./app
    tags: 
      - latest
      - ${DRONE_TAG}
- name: deploy
  image: sinlead/drone-kubectl
  settings:
    kubernetes_server:
      from_secret: k8s_server
    kubernetes_cert:
      from_secret: k8s_cert
    kubernetes_token:
      from_secret: k8s_token
  commands:
    - sed -i 's^robbof/homepage^robbof/homepage:${DRONE_TAG}^g' k8s/deployment.yml
    - kubectl apply -k k8s/

