---
kind: pipeline
name: default
trigger:
  branch:
  - master
steps:
  #- name: docker  
  #  image: plugins/docker
  #  settings:
  #    username:
  #      from_secret: docker_username
  #    password:
  #      from_secret: docker_password
  #    repo: robbof/homepage
  #    dockerfile: ./app/Dockerfile
  #    context: ./app
  #    tags: 
  #      - latest
  #      - ${DRONE_COMMIT_SHA}
- name: deploy
  image: sinlead/drone-kubectl
  settings:
    kubernetes_server:
      from_secret: k8s_server
    kubernetes_cert:
      from_secret: k8s_cert
    kubernetes_token:
      from_secret: k8s_token
  commands:
    - sed -i 's^robbof/homepage^robbof/homepage:${DRONE_COMMIT_SHA}^g' k8s/kustomization.yml
    - kubectl apply -k k8s/

- name: test
  image: busybox:latest
  commands:
    - ls
    - cat k8s/kustomization.yml

