image: docker:19.03.1

services:
  - docker:19.03.1-dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/robbof/homepage .
    - docker push registry.gitlab.com/robbof/homepage

deploy:
  stage: deploy
  script:
    - docker stack deploy -c docker-compose HOMEPAGE