image: docker:18.06.1

# services:
#   - docker:19.03.1-dind

before_script:
  - docker info

build:
  stage: build
  only: 
    - master
  script:
    - docker build -t registry.gitlab.com/robbof/homepage .
    - docker login -u RobboF -p $RobboPAT $CI_REGISTRY
    - docker push registry.gitlab.com/robbof/homepage

deploy:
  stage: deploy
  only: 
    - master
  script:
    - docker login -u RobboF -p $RobboPAT $CI_REGISTRY
    - docker pull registry.gitlab.com/robbof/homepage
    - docker stack deploy -c docker-compose.yml HOMEPAGE