apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
      - name: homepage
        image: robbof/homepage
        env:
        - name: REACT_APP_HASURA_SECRET
          valueFrom:
            secretKeyRef:
              name: hasura-secret
              key: hasura-secret
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: homepage
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
spec:
  routes:
    - match: "Host(`robbo.xyz`)"
      kind: Rule
      services:
      - kind: Service
        name: homepage
        namespace: homepage
        port: 80
  tls:
    certResolver: default
