apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k3s-demo
  template:
    metadata:
      labels:
        app: k3s-demo
    spec:
      containers:
      - name: k3s-demo
        image: registry.gitlab.com/robbof/homepage
        env:
        - name: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
          value: "true"
        - name: REACT_APP_HASURA_SECRET
          valueFrom:
            secretKeyRef:
              name: hasura-secret
              key: hasura-secret
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: k3s-demo
  namespace: default
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: k3s-demo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k3s-demo
  annotations:
    kubernetes.io/ingress.class: "traefik"

spec:
  rules:
  - host: robbo.xyz
    http:
      paths:
      - path: /
        backend:
          serviceName: k3s-demo
          servicePort: http

