apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: homepage
namePrefix: homepage-
namespace: homepage
resources:
- ./k8s/deployment.yml
- ./k8s/ingressRoute.yml
- ./k8s/service.yml

