apiVersion: v1
kind: Namespace
metadata:
  name: homepage
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: homepage
  name: homepage-deployer
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get"]
- apiGroups: ["traefik.containo.us"]
  resources: ["ingressroutes"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: homepage-deployer
  namespace: homepage
subjects:
- kind: ServiceAccount
  name: homepage-deployer
  namespace: default
roleRef:
  kind: Role
  name: homepage-deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage-deployer
  namespace: homepage
