apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    spec:
      containers:
      - name: homepage
        image: robbof/homepage
        imagePullPolicy: Always
      imagePullSecrets:
      - name: regcred
