kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: homepage-deployer
  namespace: homepage
subjects:
- kind: ServiceAccount
  name: homepage-deployer
  namespace: homepage
roleRef:
  kind: Role
  name: homepage-deployer
  apiGroup: rbac.authorization.k8s.io
