kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: homepage
  name: homepage-deployer
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","create"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","create"]
- apiGroups: ["traefik.containo.us"]
  resources: ["ingressroutes"]
  verbs: ["get","create"]
