name: Build Test Deploy
on: 
  push:
    branches:
      - master
jobs:
  Build-Test-Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install
      run: npm install
    - name: Test
      run: npm test
    - name: Build
      run: npm build
    - name: Upload to S3
      run: |
        aws s3 sync ./build s3://test-bucket
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-west-2'
    - name: Deploy
      run: aws s3 sync build/ s3://robbo